parameters:

services:
    asm_markdown_content.parser_manager:
        class: Asm\MardownContentBundle\Parser\ParserManager

    asm_markdown_content.parsedown_parser
        class: Asm\MarkdownContentBundle\Parser\ParsedownParser
        tags:
            - { name: asm_markdown_content.parser, alias: parsedown }
